[project]
name = "rgb-thresholding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "opencv-python>=4.10.0.84",
    "screeninfo>=0.8.1",
]
